services:
  - type: web
    name: truman-rec-combined
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      npm install
    startCommand: |
      python app.py & \
      python nutrition_app.py & \
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 3000
