services:
  - type: web
    name: truman-rec-combined
    env: node
    buildCommand: |
      npm install
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 3000
    staticPublishPath: ./
