services:
  - type: web
    name: truamn
    env: node
    buildCommand: |
      npm install
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    staticPublishPath: ./public
